Publicizer Support
sepluginloader/PluginLoader pull request #61
Opened 2024-05-06 20:46 UTC by SpaceGT

This PR creates publicized references for the compiler if a plugin `IgnoresAccessChecksTo` that reference.
If a plugin does not use `IgnoresAccessChecksTo` then it has no effect.

2024-11-29 16:25 UTC, StarCpt commented
RoslynCompiler.customReferences isn't used for anything but it's not concatenated to the references before compilation anymore, might be a good idea to remove it completely to reduce future confusion.

2024-12-15 10:11 UTC, viktor-ferenczi requested changes
This needs a bit of documentation here. It was tricky to write a test project to build properly.

Separate the code a bit more and call from the existing code, some methods had become a bit of spaghetti. It would also help re-reviewing this. All the publicizer related code should live in its own folder, then only called wherever needed. It is "waved" in before the compilation when references are collected, that needs to be done in a more concise, readable way.

Add documentation to both template projects to describe the plugin developer's side:
- Add dependency on `Krafs.Publicizer` package
- Add the attribute to the assembly.

Alternatively just do this in the templates, it just won't matter if not used by a plugin (see below why).

Read the directives of `Krafs.Publicizer` from the `.csproj` file and publicize only the explicitly declared types, methods, fields and properties. No need to support regex syntax. Alternatively consider calling Krafs code to publicize if that supports in-memory operation and the required code is publicly accessible. PluginLoader can depend on NuGet packages like Krafs.

2024-12-15 10:11 UTC, viktor-ferenczi requested changes
This needs a bit of documentation here. It was tricky to build a test project to build properly.

Separate the code a but and call from the existing code, some methods had become a bit of spaghetti. It would also help re-reviewing this. All the publicizer related code should live in its own folder, then only called wherever needed. It is "waved" in before the compilation when references are collected, that needs to be done in a more concise, readable way.

Add documentation to both template projects to describe the plugin developer's side: Add dependency on `Krafs.Publicizer` package, the add the attribute to the assembly.

Read the directives of `Krafs.Publicizer` from the `.csproj` file and publicize only the explicitly declared types, methods, fields and properties. No need to support regex syntax. Alternatively consider calling Krafs code to publicize if that supports in-memory operation and the required code is publicly accessible. PluginLoader can depend on NuGet packages like Krafs.

2024-12-15 10:20 UTC, viktor-ferenczi commented
You can use this new plugin as a test project:
https://github.com/viktor-ferenczi/se-better-terminal

2024-12-15 20:17 UTC, viktor-ferenczi commented
Added new plugin **Better Terminal** to Plugin Hub for testing the publicizer support in Plugin Loader. 

The plugin is set to be **hidden**, so it must be searched explicitly.

2024-12-19 07:48 UTC, viktor-ferenczi requested changes
Built and tested OK with the Better Terminal plugin (still unlisted).

I'm going to create a PR to your PR with the refactoring needed to clearly separate this code in the Roslyn related classes to make it more readable, thus easier to review by Avaness. Once that PR is merged into your branch I will ask Avaness for a review and we give it a green light, finally.

Once this PR is merged I plan to make another PR to add support for parsing the `Krafs.Publicizer` properties from the project files. This will be needed to avoid any possible future issues with publicizing everything. It causes ambiguity warnings in Better Terminals during compilation, but it succeeds and the resulting binary works. However, I don't know whether it must be the case for all future plugins depending on it.

2024-12-19 16:10 UTC, viktor-ferenczi approved these changes
Tested OK with the Better Terminal plugin both using a local development folder and online source.

2025-02-25 03:55 UTC, austinvaness commented
I apologize for taking so long on this but this is simply out of scope for this project and a violation of what I believe to be a core principle: the principle of extending, not modifying assemblies.

2025-02-25 03:55 UTC, closed without merging

2025-02-25 03:57 UTC, austinvaness commented
The Plugin Loader v1 repo is now bug fixes only and will no longer get any new features so that I can continue to work on Plugin Loader v2.